language: go
go:
  - 1.x
  - "1.16"
  - 1.16.x
  - master
notificaitons:
  email:
    recipients: msawjk@gmail.com
    on_success: change
    on_failure: always
before_script:
  - go get github.com/muhammadisa/go-transformer